type Query {
  my: User
}
type Avatar {
  medium: String
  small: String
}
type User {
  id: ID!
  name: String!
  username: String!
  avatar: Avatar
  posts: [Post]
}
type Like {
  id: ID!
  post: Post!
  user: User!
}
type PostLikes {
  total: Int!
  currentUserLiked: Boolean!
  records: [Like]
}
type Post {
  id: ID!
  author: User!
  body: String
  date: String!
  likes: PostLikes
}
